export function buildListenerHtml(pluginHandle: string): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>澄的 Telegram Listener</title><style>
  body{font-family:system-ui,sans-serif;margin:0;padding:12px;background:transparent;color:CanvasText}.card{border:1px solid color-mix(in srgb,CanvasText 16%,transparent);border-radius:14px;padding:14px}button{font:inherit;padding:8px 14px;border-radius:10px;border:1px solid color-mix(in srgb,CanvasText 20%,transparent);background:Canvas;cursor:pointer}.status{margin-top:10px;font-size:12px;opacity:.72}
  </style></head><body><div class="card"><strong>ChengLetter Listener</strong><div style="margin-top:8px"><button id="toggle">开始监听</button></div><div id="status" class="status">卡片已加载，尚未监听。</div></div><script>(()=>{
  const HANDLE=${JSON.stringify(pluginHandle)};let seq=1,timer=0,listening=false,busy=false;const pending=new Map();const status=document.getElementById('status'),toggle=document.getElementById('toggle');
  function setStatus(v){status.textContent=v}function request(method,params){const id=seq++;window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*');return new Promise((resolve,reject)=>{pending.set(id,{resolve,reject});setTimeout(()=>{const p=pending.get(id);if(!p)return;pending.delete(id);reject(new Error(method+' timeout'))},18000)})}
  addEventListener('message',event=>{if(event.source!==parent)return;const m=event.data;if(!m||m.jsonrpc!=='2.0'||m.id===undefined||!pending.has(m.id))return;const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(m.error.message||'host error')):p.resolve(m.result)},{passive:true});
  const call=(name,args={})=>request('tools/call',{name,arguments:args});
  async function dispatch(event){await request('ui/update-model-context',{content:[{type:'text',text:String(event.modelContext||'')}],structuredContent:{bridgeEvent:{eventId:String(event.id),kind:String(event.kind),source:String(event.source),createdAt:String(event.createdAt)}}});const route=String(HANDLE||'').trim();const prefix=route?(route.startsWith('@')?route:'@'+route):'';await request('ui/message',{role:'user',content:[{type:'text',text:[prefix,String(event.visibleText||'').trim()].filter(Boolean).join('\\n\\n')}]})}
  async function sync(){if(!listening||busy)return;busy=true;try{const result=await call('bridge_listener_sync');const event=result&&result._meta&&result._meta.event;if(!event){setStatus('监听中，暂无新消息。');return}try{setStatus('正在送入 '+event.id+'…');await dispatch(event);await call('bridge_listener_delivered',{eventId:String(event.id)});setStatus('已送入 '+event.id)}catch(error){await call('bridge_listener_release',{eventId:String(event.id)}).catch(()=>{});throw error}}catch(error){setStatus('监听异常：'+(error&&error.message?error.message:String(error)))}finally{busy=false}}
  function schedule(){clearInterval(timer);if(!listening)return;timer=setInterval(()=>void sync(),8000)}toggle.addEventListener('click',()=>{listening=!listening;toggle.textContent=listening?'暂停监听':'开始监听';setStatus(listening?'监听中…':'已暂停。');schedule();if(listening)void sync()});addEventListener('focus',()=>{if(listening)void sync()});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&listening)void sync()});
  })();</script></body></html>`;
}
